// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
export const top100Films = [
    { label: 'The Shawshank Redemption', id: 0 },
    { label: 'The Godfather', id: 1 },
    { label: 'The Godfather: Part II', id: 2 },
    { label: 'The Dark Knight', id: 3 },
    { label: '12 Angry Men', id: 4 },
    { label: "Schindler's List", id: 5 },
    { label: 'Pulp Fiction', id: 6 },
    {
      label: 'The Lord of the Rings: The Return of the King',
      id: 7,
    },
    { label: 'The Good, the Bad and the Ugly', id: 8 },
    { label: 'Fight Club', id: 9 },
    {
      label: 'The Lord of the Rings: The Fellowship of the Ring',
      id: 10,
    },
    {
      label: 'Star Wars: Episode V - The Empire Strikes Back',
      id: 11,
    },
    { label: 'Forrest Gump', id: 12 },
    { label: 'Inception', id: 13 },
    {
      label: 'The Lord of the Rings: The Two Towers',
      id: 14,
    },
    { label: "One Flew Over the Cuckoo's Nest", id: 15 },
    { label: 'Goodfellas', id: 16 },
    { label: 'The Matrix', id: 17 },
    { label: 'Seven Samurai', id: 18 },
    {
      label: 'Star Wars: Episode IV - A New Hope',
      id: 19,
    },
    { label: 'City of God', id: 20 },
    { label: 'Se7en', id: 21 },
    { label: 'The Silence of the Lambs', id: 22 },
    { label: "It's a Wonderful Life", id: 23 },
    { label: 'Life Is Beautiful', id: 24 },
    { label: 'The Usual Suspects', id: 25 },
    { label: 'Léon: The Professional', id: 26 },
    { label: 'Spirited Away', id: 27 },
    { label: 'Saving Private Ryan', id: 28 },
    { label: 'Once Upon a Time in the West', id: 29 },
    { label: 'American History X', id: 30 },
    { label: 'Interstellar', id: 31 },
    { label: 'Casablanca', id: 32 },
    { label: 'City Lights', id: 33 },
    { label: 'Psycho', id: 34 },
    { label: 'The Green Mile', id: 35 },
    { label: 'The Intouchables', id: 36 },
    { label: 'Modern Times', id: 37 },
    { label: 'Raiders of the Lost Ark', id: 38 },
    { label: 'Rear Window', id: 39 },
    { label: 'The Pianist', id: 40 },
    { label: 'The Departed', id: 41 },
    { label: 'Terminator 2: Judgment Day', id: 42 },
    { label: 'Back to the Future', id: 43 },
    { label: 'Whiplash', id: 44 },
    { label: 'Gladiator', id: 45 },
    { label: 'Memento', id: 46 },
    { label: 'The Prestige', id: 47 },
    { label: 'The Lion King', id: 48 },
    { label: 'Apocalypse Now', id: 49 },
    { label: 'Alien', id: 50 },
    { label: 'Sunset Boulevard', id: 51 },
    {
      label: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
      id: 52,
    },
    { label: 'The Great Dictator', id: 53 },
    { label: 'Cinema Paradiso', id: 54 },
    { label: 'The Lives of Others', id: 55 },
    { label: 'Grave of the Fireflies', id: 56 },
    { label: 'Paths of Glory', id: 57 },
    { label: 'Django Unchained', id: 58 },
    { label: 'The Shining', id: 59 },
    { label: 'WALL·E', id: 60 },
    { label: 'American Beauty', id: 61 },
    { label: 'The Dark Knight Rises', id: 62 },
    { label: 'Princess Mononoke', id: 63 },
    { label: 'Aliens', id: 64 },
    { label: 'Oldboy', id: 65 },
    { label: 'Once Upon a Time in America', id: 66 },
    { label: 'Witness for the Prosecution', id: 67 },
    { label: 'Das Boot', id: 68 },
    { label: 'Citizen Kane', id: 69 },
    { label: 'North by Northwest', id: 70 },
    { label: 'Vertigo', id: 71 },
    {
      label: 'Star Wars: Episode VI - Return of the Jedi',
      id: 72,
    },
    { label: 'Reservoir Dogs', id: 73 },
    { label: 'Braveheart', id: 74 },
    { label: 'M', id: 75 },
    { label: 'Requiem for a Dream', id: 76 },
    { label: 'Amélie', id: 77 },
    { label: 'A Clockwork Orange', id: 78 },
    { label: 'Like Stars on Earth', id: 79 },
    { label: 'Taxi Driver', id: 80 },
    { label: 'Lawrence of Arabia', id: 81 },
    { label: 'Double Indemnity', id: 82 },
    {
      label: 'Eternal Sunshine of the Spotless Mind',
      id: 83,
    },
    { label: 'Amadeus', id: 84 },
    { label: 'To Kill a Mockingbird', id: 85 },
    { label: 'Toy Story 3', id: 86 },
    { label: 'Logan', id: 87 },
    { label: 'Full Metal Jacket', id: 88 },
    { label: 'Dangal', id: 89 },
    { label: 'The Sting', id: 90 },
    { label: '2001: A Space Odyssey', id: 91 },
    { label: "Singin' in the Rain", id: 92 },
    { label: 'Toy Story', id: 93 },
    { label: 'Bicycle Thieves', id: 94 },
    { label: 'The Kid', id: 95 },
    { label: 'Inglourious Basterds', id: 96 },
    { label: 'Snatch', id: 97 },
    { label: '3 Idiots', id: 98 },
    { label: 'Monty Python and the Holy Grail', id: 99 },
  ];
  
  export default top100Films;
  